name: flutter_interview
description: Flutter recruitment task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  json_annotation: 4.6.0
  http: 0.13.5
  flutter_screenutil: 5.6.1
  flutter_bloc: 8.1.2
  equatable: 2.0.5
  flutter_spinkit: 5.1.0
  fluttertoast: 8.0.9
  retrofit: 4.0.1
  dio: 5.0.0
  injectable: 2.1.0
  get_it: 7.2.0
  rxdart: 0.27.5
  intl: 0.17.0
  auto_route: 5.0.2
  easy_localization: 3.0.1
  keyboard_dismisser: 3.0.0
  freezed: 2.3.2
  copy_with_extension: 4.0.3
  infinite_scroll_pagination: 3.2.0
  cached_network_image: 3.2.1
  bloc_test:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  build_runner: 2.3.3
  json_serializable: 6.3.2
  retrofit_generator: 5.0.0
  injectable_generator: 2.1.4
  flutter_launcher_icons: 0.10.0
  auto_route_generator: 5.0.3
  mocktail:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/x2/
    - assets/translations/
  fonts:
    - family: Roboto
      fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Medium.ttf
      - asset: assets/fonts/Roboto-Bold.ttf
      - asset: assets/fonts/Roboto-Light.ttf
    - family: SF
      fonts:
      - asset: assets/fonts/SF-Pro-Display-Regular.otf
      - asset: assets/fonts/SF-Pro-Display-Bold.otf
      - asset: assets/fonts/SF-Pro-Display-Medium.otf

